name: 'Create Semantic Version Tag'
description: 'Creates a new semantic version tag based on commit messages'
inputs:
  github-token:
    description: 'GitHub token for creating tags'
    required: true
  default-bump:
    description: 'Default version bump if not detected (major, minor, patch)'
    required: false
    default: 'patch'
  tag-prefix:
    description: 'Prefix for version tags'
    required: false
    default: 'v'
  dry-run:
    description: 'Run without creating the tag'
    required: false
    default: 'false'
outputs:
  new-tag:
    description: 'The new version tag created'
    value: ${{ steps.tag.outputs.new_tag }}
  previous-tag:
    description: 'The previous version tag'
    value: ${{ steps.tag.outputs.previous_tag }}
  bump:
    description: 'The type of version bump applied'
    value: ${{ steps.tag.outputs.bump }}
runs:
  using: 'composite'
  steps:
    - name: Get latest tag
      id: get-latest-tag
      shell: bash
      run: |
        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -z "$LATEST_TAG" ]; then
          echo "No previous tags found, starting with v0.0.0"
          LATEST_TAG="${{ inputs.tag-prefix }}0.0.0"
        fi
        echo "previous_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "Previous tag: $LATEST_TAG"

    - name: Determine version bump
      id: bump
      shell: bash
      run: |
        # Get commits since last tag
        PREVIOUS_TAG="${{ steps.get-latest-tag.outputs.previous_tag }}"

        if [ "$PREVIOUS_TAG" = "${{ inputs.tag-prefix }}0.0.0" ]; then
          COMMITS=$(git log --pretty=format:"%s" HEAD)
        else
          COMMITS=$(git log --pretty=format:"%s" ${PREVIOUS_TAG}..HEAD)
        fi

        echo "Analyzing commits:"
        echo "$COMMITS"

        # Determine bump type based on conventional commits
        BUMP="${{ inputs.default-bump }}"

        if echo "$COMMITS" | grep -qiE "^(BREAKING CHANGE:|feat!:|fix!:|chore!:|docs!:)"; then
          BUMP="major"
        elif echo "$COMMITS" | grep -qiE "^feat(\(.+\))?:"; then
          BUMP="minor"
        elif echo "$COMMITS" | grep -qiE "^(fix|perf|refactor)(\(.+\))?:"; then
          BUMP="patch"
        fi

        echo "bump=$BUMP" >> $GITHUB_OUTPUT
        echo "Version bump type: $BUMP"

    - name: Calculate new version
      id: tag
      shell: bash
      run: |
        PREVIOUS_TAG="${{ steps.get-latest-tag.outputs.previous_tag }}"
        BUMP="${{ steps.bump.outputs.bump }}"
        PREFIX="${{ inputs.tag-prefix }}"

        # Remove prefix to get version numbers
        VERSION=${PREVIOUS_TAG#$PREFIX}

        # Split version into components
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

        # Increment based on bump type
        case $BUMP in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH + 1))
            ;;
        esac

        NEW_TAG="${PREFIX}${MAJOR}.${MINOR}.${PATCH}"

        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
        echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
        echo "bump=$BUMP" >> $GITHUB_OUTPUT

        echo "New version: $NEW_TAG"

    - name: Create and push tag
      if: inputs.dry-run == 'false'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        NEW_TAG="${{ steps.tag.outputs.new_tag }}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
        git push origin "$NEW_TAG"

        echo "✅ Created and pushed tag: $NEW_TAG"

    - name: Dry run summary
      if: inputs.dry-run == 'true'
      shell: bash
      run: |
        echo "🔍 DRY RUN - Tag would be created: ${{ steps.tag.outputs.new_tag }}"
        echo "Previous: ${{ steps.tag.outputs.previous_tag }}"
        echo "Bump: ${{ steps.tag.outputs.bump }}"
